### ISSUE TITLE
发送图片会出现这个错误

### ISSUE THREAD

**Issue by 661111** [TimeRainStarSky/Yunzai-QQGuild-Plugin#11]
![Screenshot_2024-03-21-20-49-59-48_ac18b4ac776c2206cd098a661f696307](https://github.com/TimeRainStarSky/Yunzai-QQGuild-Plugin/assets/108344166/0d292004-9e9d-409c-abdd-f398c01b7a95)
如图片所示

**Comment by TimeRainStarSky** [comment]
更新Node.js

**Comment by 661111** [comment]
node 版本要更新到多少

**Comment by TimeRainStarSky** [comment]
> node 版本要更新到多少

21以上
