### ISSUE TITLE
私聊报错

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [TimeRainStarSky/Yunzai-QQGuild-Plugin#6]
![image](https://github.com/TimeRainStarSky/Yunzai-QQGuild-Plugin/assets/117198625/d29d59bf-ef01-458b-9c25-e65cf87e5266)

**Comment by TimeRainStarSky** [comment]
上下文

**Comment by S-t-e-v-e-e** [comment]
![image](https://github.com/TimeRainStarSky/Yunzai-QQGuild-Plugin/assets/117198625/9b552608-b39d-49a9-8b4b-68327de8f43d)

**Comment by TimeRainStarSky** [comment]
检查频道设置私聊限制
